[SMTP]
# Konfiguracja serwera do wysylki e-maili
server = mail.uzp.gov.pl.int
port = 587
user = glpihelpdesk@uzp.gov.pl
password = gAAAAABo0SyKd57h8HmhjiOfyqk755y2MMtC3vZ8ZiQMotJZMcVbPFgTOnVhBfj0CiGccBvOLytxPrPzLCdUZWJhOwhM7Zlf4w==
use_tls = true
sender_email = glpihelpdesk@uzp.gov.pl

[EMAILS]
recipient_email_toner_low = lukasz.kurenda@uzp.gov.pl
recipient_email_toner_critical = lukasz.kurenda@uzp.gov.pl
recipient_email_counters = lukasz.kurenda@uzp.gov.pl
recipient_email_errors = lukasz.kurenda@uzp.gov.pl

[MONITORING]
# Glowne ustawienia skryptu
printers_file = printers.csv
log_file = printer_monitor.log
toner_threshold_low = 5
toner_low_status_percent = 5
toner_threshold_critical = 1
snmp_community = public
toner_filter_keywords = toner, kaseta, cartridge, tusz
toner_exclude_keywords = waste,beben,developer,fuser,utrwalajacy,obraz,konserwacyjny,maintenance,roller,limiter
snmp_timeout = 2
snmp_retries = 2
snmp_port = 161

[WWW]
chrome_binary = /home/jules/.cache/ms-playwright/chromium-1181/chrome-linux/chrome
headless = true

# Dzien miesiaca (1-31), w ktorym ma byc wysylany raport licznikow
report_day = 1

[CUSTOM_OIDS:172.20.12.152]
oid_desc = 1.3.6.1.2.1.43.11.1.1.6.1
oid_max = 1.3.6.1.2.1.43.11.1.1.8.1
oid_current = 1.3.6.1.2.1.43.11.1.1.9.1

[CUSTOM_OIDS:172.20.12.245]
# Aby włączyć precyzyjny odczyt liczników dla tej drukarki,
# znajdź odpowiednie OID-y (np. za pomocą snmpwalk) i uzupełnij poniższe pola.
oid_color_count =
oid_bw_count =
